bitfocus/companion-module-figure53-qlab-advance

- HELP.md
- package.json
- qlabfb.js
Several fixes, cleanup, and improvements in this update. 
Should cover most of the request for QLab feedbacks [here](https://github.com/bitfocus/companion-module-qlab/issues/8)
> Improvements for QLab with feedback and variables

- HELP.md
- package.json
- qlabfb.js
New features:
- Added UDP mode with TCP mode checkbox*.
- Added Show mode on/off action.
- Added Audition window show/hide action.
- Feedback for workspace mode. Choose colors based on Audition, Show, Edit status.
* Variables and feedback require TCP and will increase network traffic.
> Feature update

- HELP.md
- package.json
- qlabfb.js
Added several variables to show remaining time on currently running cue for #3
> Remaining time for cue (Feature request #3)

- HELP.md
- package.json
- qlabfb.js
Added Q name variables
updated HELP
version bump
> Q vars, HELP, version

- package.json
- qlabfb.js
Properly dispose of dynamic variables on disable/destroy
Cosmetic/lint
Clear reconnect timer on disable/destroy
> Minor cleanup

- package.json
> remove osc dependency

- qlabfb.js
More log clutter reduction.
Won't update feedback if value didn't change.
More complete removal of timers and sockets when module is disabled.
> Button updates & better shutdown

- HELP.md
- actions.js
- colors.js
- cues.js
- feedbacks.js
- package.json
- presets.js
- qlabfb.js
- variables.js
Adds support for feature #21 and feature #26.
Instance help update to correspond with recent feature additions.
Four more colors added, version bump.
> Variables for specific cuelist and cue notes

- HELP.md
- actions.js
- presets.js
- qlabfb.js
Opens up for editing the Start Time and End Time of the selected cue by given seconds. Contains preset for Inc and Dec of 1 and 10 sec on both Start Time and End Time. Same PR is created in the regular Qlab module
> Support for adjusting Start and End Time

- package.json
- presets.js
Final inclusion of features from the original `qlab` module.
> Added icons to some presets, version bump

- HELP.md
- package.json
- qlabfb.js
Bugfix for an improper type comparison
Reduce some unnecessary network traffic
> Correct type mismatch, more traffic tuning

- package.json
- qlabfb.js
Adding the ability to select a specific cue list lost proper cue time feedback.
This re-enables the timer.
> Fix missing cue timer feedback

- HELP.md
- package.json
- qlabfb.js
This should fix anomalies discovered in #42.
> Rewrite logic for specific Cue List control

- HELP.md
- actions.js
- feedbacks.js
- package.json
- presets.js
- qlabfb.js
- variables.js
Implements #41.
Action to set Minimum time between Gos value.
Variable for Minimum Go time
Feedback color to indicate Go disabled during time window
Preset for a Color-coded Go button
Docs updated
Some code consolidation.
> Add double-go button feedback

- actions.js
- colors.js
- cues.js
- feedbacks.js
- package.json
- presets.js
- qlabfb.js
- variables.js
Use instance provided `self.rgb`
Refactor `require` of local modules to user correct `this`
> Replace global rgb with self.rgb

- HELP.md
- package.json
- qlabfb.js
Only shows the first connection error instead of every 5 seconds.
Added Help for new commands
> Prevent repeated logging

- HELP.md
- actions.js
- choices.js
- cues.js
- feedbacks.js
- package.json
- qlabfb.js
Feature #46 
Consolidate some code
Redo internal logic that determines which 'cue' is playing for timers.
Add collection and toggle for recent hold and loop commands.
> Add Master Override Options

- HELP.md
- feedbacks.js
- package.json
- qlabfb.js
Requested via facebook and in #46
> Added Feedback for Cue is Running

- feedbacks.js
- package.json
- presets.js
- qlabfb.js
- variables.js
Added elapsed time variables (Facebook request)
Updated some feedbacks to boolean style
Version bump
> Add elapsed time and boolean feedback

- cues.js
- feedbacks.js
- package.json
- qlabfb.js
Fixes issue #64 
Substitute [none] when cue name is undefined/empty.
> Fix cue number isRunning feedback

- HELP.md
- package.json
> Update docs to include new variable

- package.json
- qlabfb.js
Argh. This was supposed to be in the prior updates. Apparently stashed but not re-applied.
> Bugfix: Re-add checks for 'undefined'

- .gitignore
- package.json
- presets.js
Added missing (required) elements for v3 compatability.
Version bump
> Fix: preset buttons missing since upgrade to v3

- companion/HELP.md
- package.json
- upgrades.js
Fix docs to properly open link
Typo? in upgrade script?
> Docs, typo in upgrade script

- yarn.lock
> module update

- package.json
> version bump again

- actions.js
- companion/HELP.md
- package.json
Adds 'Audition' preview command for QLab5
> Missed a command for the last feature update

- package.json
- qlabfb.js
> Fix missing 'hidden' name variables

- actions.js
- choices.js
- cues.js
- feedbacks.js
- package.json
- qlabfb.js
- yarn.lock
Beginning to add options to actions to specify target (selected/playhead/cue number/cue ID)
Includes #115
> Refactor actions scope to include cue num and ID

- actions.js
- companion/HELP.md
- package.json
- qlabfb.js
Check/update recent updates for QLab4 compatibility.
Update docs to include new actions/feedbacks
> Q4 compatablility. Update Docs.

- actions.js
- package.json
- qlabfb.js
> Better detection of passcode issues. Validate certain action options

- actions.js
- choices.js
- feedbacks.js
- package.json
- presets.js
- qlabfb.js
Fix logic for new scoped actions and feedbacks
Fix errors when using specific cuelist via config.
> Fix scope fb/actions and a cuelist bug

- actions.js
- feedbacks.js
- package.json
- presets.js
> Fixed typos preventing feedback on 'Is Flagged'

- package.json
- qlabfb.js
Fix improper variable definition that would crash initial config for UDP mode
> Fix UDP crash #143

- README.md
- actions.js
- choices.js
- companion/HELP.md
- feedbacks.js
- package.json
- qlabfb.js
Per #145 
Adds variables for Cue 'Name' and 'Elapsed' time (in seconds)
> Add 'Select cue' actions, isSelected feedback

- companion/HELP.md
- feedbacks.js
- package.json
- qlabfb.js
- variables.js
Adds feedback for `Selected` cues.
Fixes incorrect cue selection for some scoped actions
Adds a Total Seconds variable for elapsed and remaining times.
> Fix regression for elapsed/remaining times

- companion/HELP.md
- package.json
- qlabfb.js
Also adds `q_{num}_id` variable that holds the Unique ID of cue {num} 
Completes #153
> Finish cleanup of configured workspace and cuelist issues

- actions.js
- package.json
- qlabfb.js
Consolidate test for cuelist prefix on OSC commands
> More cuelist refactor

- companion/HELP.md
- package.json
- qlabfb.js
Revert running cue times to values based on `pctElapsed`
> Calc 'elapsed' variables from 'pctElapsed'

- package.json
- qlabfb.js
Query response differences between QLab5 and QLab4 caused errors when using QLab4.
Updated to support both versions.
> Backport selected cue features to QLab 4
